In [11]:
import sys
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import pickle

In [12]:
import pandas.core.indexes
sys.modules['pandas.indexes'] = pandas.core.indexes

In [13]:
print("Downloading dataset from Kaggle...")
path = kagglehub.dataset_download("qingyi/wm811k-wafer-map")
print(f"Dataset downloaded to: {path}")

Dataset downloaded to: /Users/udayan/.cache/kagglehub/datasets/qingyi/wm811k-wafer-map/versions/1


In [9]:
#Making the file path and loading the file in this venv
file_path = os.path.join(path, 'LSWMD.pkl')

print("Loading dataset with latin1 encoding (this might take a minute)...")
with open(file_path, 'rb') as f:
    df = pickle.load(f, encoding='latin1')
print(f"Success! Total wafers in dataset: {len(df)}")

Loading dataset with latin1 encoding (this might take a minute)...


/var/folders/_b/4pz7ygss6y7c564mcqz3grmw0000gn/T/ipykernel_3677/1757211552.py:6: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  df = pickle.load(f, encoding='latin1')


Success! Total wafers in dataset: 811457


In [14]:
# 1. Clean the nested failure type column to create 'failure_class'
df['failure_class'] = df['failureType'].apply(lambda x: x[0][0] if len(x) > 0 else 'None')

# 2. Filter out the perfect wafers to create the 'defective_wafers' subset
defective_wafers = df[(df['failure_class'] != 'None') & (df['failure_class'] != 'none')]

print("Data cleaned! Now you can view it.")

Data cleaned! Now you can view it.


In [ ]:
#first look at the data
print("Top 5 rows of the dataset:")
display(df[['waferMap', 'dieSize', 'failure_class']].head())

# Look at exactly what the 2D array looks like for the first defective wafer
first_defect_index = defective_wafers.index[0]
first_defect_array = defective_wafers.loc[first_defect_index, 'waferMap']

print("\nShape of the first defective wafer array:", first_defect_array.shape)
print("\nThe raw 2D array data (Notice the 0s, 1s, and 2s):")
print(first_defect_array)

Top 5 rows of the dataset:


,waferMap,dieSize,failure_class
0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,none
1,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,none
2,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,none
3,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,none
4,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,none



Shape of the first defective wafer array: (45, 48)

The raw 2D array data (Notice the 0s, 1s, and 2s):
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
# Force NumPy to print the entire array without truncation
np.set_printoptions(threshold=10000)

print("The FULL raw 2D array data:")
print(first_defect_array)

# Reset it back to default right after so future arrays don't break your terminal
np.set_printoptions(threshold=1000)

The FULL raw 2D array data:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 2 1 1 2 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1
  0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2
  1 1 1 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1
  1 2 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1